### PR TITLE
added form file

### PR DESCRIPTION
**Pull request by Aman1143**
Issue: 28

### CODE REVIEW

**Review by Manas2403 — CHANGES_REQUESTED** [review]
@Aman1143  do the changes according to the Issue description

**Comment by Manas2403** [comment]
If you want to give up the issue please tell @Aman1143

**Comment by Aman1143** [comment]
No , I will try to change .

**Comment by Aman1143** [comment]
@Manas2403 I changed the functionality in email and domain input field .
If you want any change let me know.

**Comment by Manas2403** [comment]
@Aman1143  deployment has failed. There are errors in your code 
image

**Comment by Manas2403** [comment]
Also why have you cretead a new file From.js ?

**Comment by Manas2403** [comment]
It is  clearly mentioned in issue description where to write your code.

**Comment by Aman1143** [comment]
ok I am deleting this file

**Review by Manas2403 — CHANGES_REQUESTED** [review]
I told you yesterday what fields we want and color theme is also not followed. Also the page is not responsive for mobile screen.

**Comment by Aman1143** [comment]
Is this ok ??

**Pull request merged**
