### PR TITLE
get user dashboard

### PR DESCRIPTION
**Pull request by SanyamAgrawal07**
Issue: 102

#### Changes proposed in this pull request and/or Screenshots of changes:

-
-
-

### CODE REVIEW

**Review by Manas2403 — CHANGES_REQUESTED** [review]
Add a check if you do not get access token redirect to signin page. and there is some error in build on vercel. Check if you are getting some error on local also.

**Comment by SanyamAgrawal07** [comment]
@Manas2403 I have made the changes and checked, it is redirecting successfully. Please review

**Review by Manas2403 — CHANGES_REQUESTED** [review]
try by not sending the access token in get request

**Comment by SanyamAgrawal07** [comment]
@Manas2403 like this?

**Review by Manas2403 — CHANGES_REQUESTED** [review]
You have to use useEffect hook to call the function. Don't use then

**Pull request merged**
