### PR TITLE
Alert banner

### PR DESCRIPTION
**Pull request by hargunkaur286**
Issue: 69

added alert banner
Screen Shot 2022-12-24 at 8 21 37 PM

### CODE REVIEW

**Review by Manas2403 — CHANGES_REQUESTED** [review]
Have you used the packages you installed anywhere ?

**Comment by hargunkaur286** [comment]
> Have you used the packages you installed anywhere ?

Yes, I have used flowbite. It is used to dismiss the banner

**Comment by Manas2403** [comment]
But banner can be dismissed by settting a useState variable like if user clicks on close icon the state can be set to false and instead of returning the component you can directly return.  I want  you to try that way, give a try to it.

**Comment by hargunkaur286** [comment]
> But banner can be dismissed by settting a useState variable like if user clicks on close icon the state can be set to false and instead of returning the component you can directly return. I want you to try that way, give a try to it.

I tried it, but I am not able to do it without using any package

**Review by Manas2403 — APPROVED** [review]

**Pull request merged**
