### PR TITLE
fix for issue #103 : added all things that were asked

### PR DESCRIPTION
**Pull request by MistyRavager**
Issue: 103

#### Short description of what this resolves:
added all validation conditions. Also if someone hits cancel, all input fields are erased. added patch request

#### Changes proposed in this pull request and/or Screenshots of changes:

- add patch function on API folder

### CODE REVIEW

**Review by Manas2403 — CHANGES_REQUESTED** [review]
image
@MistyRavager  when i click the submit button, there is error plz test once. U can create your new account on signup page and try to change the password

**Comment by MistyRavager** [comment]
That is only because there is no 'patch' function in the API folder. On discord you told that you will create the patch request method....so i just put that here assuming you will create the function with name 'patch'

**Comment by Manas2403** [comment]
Added patch function can you just check now if it is working properly @MistyRavager

**Comment by MistyRavager** [comment]
Updated code, it does put a patch request but it fails the authentication middleware in _backend_  because authentication is not applied yet ig

**Review by Manas2403 — APPROVED** [review]

**Pull request merged**
